### ISSUE TITLE
Incorporating Medium tags into Frontmatter

### ISSUE THREAD

**Issue by agcode** [gautamdhameja/medium-2-md#1]
It would be wonderful if the tags that are present in a medium post could be incorporated in the front matter.

**Comment by gautamdhameja** [comment]
Unfortunately, the tags are not available in the exported Medium posts (HTML). I wrote about this in the related blog post:

> A couple of things that we need to take care of manually are code fences and tags. There is no tag related information in the exported Medium files. The code fences are also exported as plain text and the markdown conversion ignores them too.

Read more here: https://www.gautamdhameja.com/medium-to-markdown-converter/

**Comment by agcode** [comment]
Thank you for the quick reply. I should have seen that - rereading the blog now.

Though the information is not present in the exported files, I wonder if it would be possible to extract tags with the convertUrl option.

**Comment by gautamdhameja** [comment]
I'll check if it could be done for the `convertUrl` option. Thanks for pointing this out.

**Comment by gautamdhameja** [comment]
Addressed in version 0.3.0 - https://www.npmjs.com/package/medium-2-md/v/0.3.0. 
Closing this issue.

**Comment by agcode** [comment]
Thank you very much
