### ISSUE TITLE
Image Captions

### ISSUE THREAD

**Issue by agcode** [gautamdhameja/medium-2-md#2]
Exported Medium files have Image captions under a figcaption tag. 

`<figcaption class="imageCaption">Some Caption Goes Here </figcaption>`

At present, the conversion renders this caption as part of the all the other text present in the post. I'm aware of the markdown limitation for `![](http://image.url)`. But it would be nice to have `![Some Caption Goes Here](http://image.url)`

**Comment by gautamdhameja** [comment]
Addressed in version 0.3.0 - https://www.npmjs.com/package/medium-2-md/v/0.3.0. 
Closing this issue.

**Comment by agcode** [comment]
Thanks a lot.
