### ISSUE TITLE
Add support for "page bundles"?

### ISSUE THREAD

**Issue by thinkong** [gautamdhameja/medium-2-md#24]
Hi,

I am interested in using this to export my medium blog to a hugo blog. 
I really want to use the page bundle system in the hugo system. Could it be possible to add some support so that the exported md/images go into seperate folders?

**Comment by gautamdhameja** [comment]
Added options for custom output and image paths and published a new release. See readme for more details. Thanks for suggesting this. Cheers.
Closing this issue.
