### ISSUE TITLE
Saving Images from medium posts

### ISSUE THREAD

**Issue by agcode** [gautamdhameja/medium-2-md#3]
Would it be possible to save images from medium posts to an images folder while executing medium2md

**Comment by alexanderadam** [comment]
@agcode I stumbled about the same issue. Maybe [this script](https://gist.githubusercontent.com/tvdsluijs/21543f463d8fa1626d11f5ce01f68258/raw/7debe65aa03781464512b123e926865ef2050e30/medium2Markdown.py) from @tvdsluijs could help ([his blogpost](https://www.itheo.nl/2018-07-python-convert-medium-export-to-markdown-files/)).

**Comment by ravanscafi** [comment]
I would love this feature :)

**Comment by gautamdhameja** [comment]
Support to download images is now added in v0.4.0. Closing this issue.
https://www.npmjs.com/package/medium-2-md/v/0.4.0

**Comment by alexanderadam** [comment]
Works like charm! :+1:

**Comment by agcode** [comment]
Thank you so much.
