### ISSUE TITLE
Medium now has rate-limiting on image downloads

### ISSUE THREAD

**Issue by SimonBaars** [gautamdhameja/medium-2-md#35]
Currently, the script has no delay on image downloads. The first few article's images will fetch correctly, after which Medium rate limits and the next couple will fail.

Proposed solution is an extra argument `timeout` which delays every image fetch by a specified number of milliseconds. A default timeout of something like `100` milliseconds should fix the problem.

(I'd be happy to make this change as an open source contribution)

**Comment by gautamdhameja** [comment]
Closing as complete.
