### ISSUE TITLE
Get parameters are breaking file name generation

### ISSUE THREAD

**Issue by alexanderadam** [gautamdhameja/medium-2-md#5]
I just copied an URL from medium that contains a (weird) GET parameter:

`https://medium.com/@benlaurie_18378/how-to-ruin-a-perfectly-good-container-d33250fca595?source=---------2------------------`

When trying to archive it:
```bash
$ medium-2-md convertUrl 'https://medium.com/@benlaurie_18378/how-to-ruin-a-perfectly-good-container-d33250fca595?source=---------2------------------' -o .
```

The file will be called `.md` (and therefore hidden on *NIX systems).

PS: Maybe it could be fixed together with #4

**Comment by gautamdhameja** [comment]
I think this issue should have been only with `convertUrl` and not with `convertLocal`. Fixed in v0.4.1. https://www.npmjs.com/package/medium-2-md/v/0.4.1
