### ISSUE TITLE
Option to embed images with base64

### ISSUE THREAD

**Issue by alexanderadam** [gautamdhameja/medium-2-md#6]
It would be nice if there would be an option [to embed images with base64](https://medium.com/markdown-monster-blog/getting-images-into-markdown-documents-and-weblog-posts-with-markdown-monster-9ec6f353d8ec).

**Comment by gautamdhameja** [comment]
I don't think this should be in scope for this simple tool. All it does is to convert existing Medium files into markdown. The images are linked as-is and that should be fine. Not all users would be interested in base64 embeds of images. Closing.
