### ISSUE TITLE
Error converting file

### ISSUE THREAD

**Issue by djensen47** [gautamdhameja/medium-2-md#9]
```
Error converting file: 2016-06-03_Payette-Brewing--Idaho-Will-Be-Known-for-More-Than-Potatoes-9ac8792a37f5.html. Skipping.
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:329:15)
    at TLSSocket.socketOnEnd (_http_client.js:421:23)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

---

P.S. Thanks for making such a great tool!

**Comment by djensen47** [comment]
Let me know if you need the html file.

I think it might be because I have 215 files and maybe something is getting rate limited? Would it be possible to slow down the process of pulling the images?

**Comment by gautamdhameja** [comment]
Sorry, just saw this.

@djensen47 Yeah, please share the html file for me to debug this. Thanks.

**Comment by djensen47** [comment]
The issue here is not just one file. This happens when you have dozens of files with several images each. The call to `Promise.all` executes all of the promises at the same time. However, if I change it to be sequential, I do not get the error. I'll submit a PR for this change.
